#!/bin/bash
set -euo pipefail

_build_jar() {
  ./mvnw clean install -DskipTests
}

_publish_jar() {
  package_cloud push --url https://packages.shopify.io/ \
    --coordinates com.shopify.data.prestosql:presto-server:325 \
    shopify/public/java/1.8 \
    presto-server/target/presto-server-325-SNAPSHOT.tar.gz

  package_cloud push --url https://packages.shopify.io/ \
    --coordinates com.shopify.data.prestosql:presto-benchmark-driver:325 \
    shopify/public/java/1.8 \
    presto-benchmark-driver/target/presto-benchmark-driver-325-SNAPSHOT.tar.gz
}

main() {
  _build_jar
  _publish_jar
}

main
